name: Changelog CI CZ
description: Changelog CI generates changelog, commits and/or comments to the release PR. Follows commitizen format.
author: Maksudul Haque
branding:
  icon: 'clock'
  color: 'blue'
inputs:
  changelog_filename:
    description: 'Name of the changelog file if not provided defaults to CHANGELOG.md'
    required: false
    default: 'CHANGELOG.md'
  config_file:
    description: 'Location of the config JSON file'
    required: false
  committer_username:
    description: 'Name of the user who will commit the changes to GitHub'
    required: false
    default: 'github-actions[bot]'
  committer_email:
    description: 'Email Address of the user who will commit the changes to GitHub'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  release_version:
    description: 'The release version that will be used on the generated Changelog'
    required: false
  github_token:
    description: 'GITHUB_TOKEN or Personal Access Token (PAT)'
    required: false
    default: ${{ github.token }}

runs:
  using: 'docker'
  image: 'Dockerfile'
