name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check Formatting with Black
      uses: psf/black@stable

    - name: Check Typing with Mypy
      run: |
        python -m pip install mypy==0.961
        mypy --install-types .

    - name: Run Tests
      run: PYTHON_TESTENV=true python -m unittest
